export const TOGLLE__CART__DETAIL = 'TOGGLE__CART__DETAIL';
export const OPEN_FORM_SIGNUP = 'OPEN_FORM_SIGNUP';
export const OPEN_FORM_SIGNIN = 'OPEN_FORM_SIGNIN';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCT_SUCESS = 'SEARCH_PRODUCT_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const FILTER_PRODUCTS_SUCCESS = 'FILTER_PRODUCTS_SUCCESS';
